/**
 * !!! This file is generated by the gulp task build-config !!!
 */
/// <reference path="../../../../typings/tsd.d.ts" />

module my.core.constants {
  'use strict';

  export interface IAppConfig {
    ENVIRONMENT: string;
    BASE_URL: string;
    LANGUAGE: string;
  }

  angular
    .module(ID.AppConfig, [])
    .constant(ID.AppConfig, {
      ENVIRONMENT: '<%= environment %>',
      BASE_URL:    '<%= baseUrl %>',
      LANGUAGE:    '<%= language %>'
    });

}
